# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FastKDNeighbour <- function(query_, ref_, k) {
    .Call('rflann_FastKDNeighbour', PACKAGE = 'rflann', query_, ref_, k)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('rflann_RcppExport_registerCCallable', PACKAGE = 'rflann')
})
